### ISSUE TITLE
This template is no longer working, because gleam changed some parameters

### ISSUE THREAD

**Issue by edelvalle** [gleam-lang/gleam-javascript-basic-template#1]
After following instructions in the README.md

```bash
# Clone and enter the project
git clone $MY_REPO_CLONE_URL hello-gleam-js
cd hello-gleam-js

# Install the node modules
npm install

# Run the Gleam program on NodeJS
npm start
```

The [bin/build.js:57](https://github.com/gleam-lang/template-gleam-javascript/blob/cb329b4d59010aa1eb8a56a77d815390344ba74f/bin/build.js#L62) file is trying to run gleam with parameters that are no longer valid.

**Comment by lpil** [comment]
Hello! This template was intended for that version of Gleam only and is no longer required. Full JS support is now included in the build tool :)
